from __future__ import annotations

import re


_SENTENCE_END_RE = re.compile(r"[.!?]$")
_WORD_RE = re.compile(r"[\w']+")
_STOP_WORDS = {
    "a",
    "an",
    "and",
    "are",
    "as",
    "at",
    "be",
    "but",
    "by",
    "for",
    "from",
    "has",
    "have",
    "i",
    "if",
    "in",
    "into",
    "is",
    "it",
    "its",
    "of",
    "on",
    "or",
    "our",
    "that",
    "the",
    "their",
    "there",
    "this",
    "to",
    "was",
    "we",
    "were",
    "with",
    "you",
    "your",
    "about",
    "after",
    "before",
    "during",
    "then",
    "than",
    "here",
    "now",
    "yeah",
    "okay",
    "ok",
    "just",
    "really",
    "very",
    "got",
    "going",
    "go",
    "back",
    "last",
    "round",
    "team",
    "new",
    "what",
    "who",
    "when",
    "where",
    "why",
    "how",
    "im",
    "i'm",
    "ive",
    "i've",
}
_THREE_WAYS_SHOTS: tuple[tuple[str, str], ...] = (
    ("wide", "wide shot"),
    ("medium", "medium shot"),
    ("detail", "detail shot"),
)
_BROLL_TX_SLOT_ID = "__broll_transaction__"
_POSITIVE_ENERGY_WORDS = {
    "amazing",
    "awesome",
    "boom",
    "build",
    "crazy",
    "fast",
    "fire",
    "go",
    "great",
    "hype",
    "insane",
    "massive",
    "power",
    "rapid",
    "rush",
    "strong",
    "top",
    "viral",
    "win",
}
_NEGATIVE_ENERGY_WORDS = {
    "alone",
    "broken",
    "calm",
    "dark",
    "death",
    "empty",
    "fear",
    "lost",
    "pain",
    "sad",
    "silent",
    "slow",
    "soft",
    "still",
    "tired",
    "weak",
    "worry",
}
_LOCAL_VISUAL_INTENT_CUES: dict[str, set[str]] = {
    "literal_demo": {
        "app",
        "camera",
        "demo",
        "device",
        "phone",
        "product",
        "screen",
        "tutorial",
    },
    "process_step": {
        "build",
        "dashboard",
        "editing",
        "hands",
        "keyboard",
        "packing",
        "process",
        "screen",
        "testing",
        "workflow",
    },
    "environment_context": {
        "city",
        "crowd",
        "factory",
        "meeting",
        "office",
        "shop",
        "street",
        "studio",
        "warehouse",
        "workspace",
    },
    "reaction_payoff": {
        "celebration",
        "crowd",
        "growth",
        "launch",
        "result",
        "smile",
        "success",
        "team",
        "win",
    },
    "abstract_support": {"background", "bokeh", "light", "motion", "shadow", "texture"},
}
_LOCAL_SHOT_STYLE_CUES: dict[str, set[str]] = {
    "wide": {
        "city",
        "crowd",
        "factory",
        "group",
        "landscape",
        "office",
        "room",
        "shop",
        "stage",
        "street",
        "team",
        "warehouse",
        "wide",
    },
    "medium": {"desk", "host", "meeting", "person", "speaker", "studio", "team"},
    "detail": {
        "close",
        "dashboard",
        "detail",
        "device",
        "editing",
        "hands",
        "keyboard",
        "macro",
        "phone",
        "screen",
    },
}
_VISUAL_INTENT_QUERY_MODE = {
    "literal_demo": "literal",
    "process_step": "process",
    "environment_context": "environment",
    "reaction_payoff": "reaction",
    "abstract_support": "abstract",
}
_SEQUENCE_MEMORY = 4
