export const BRAND = {
  lead: "ClipMind",
  accent: "",
  productName: "ClipMind",
  shortName: "ClipMind",
  editorName: "ClipMind Editor",
  editorEyebrow: "ClipMind",
  defaultProjectName: "ClipMind Project",
  loadingTitle: "Loading ClipMind",
  landingDocumentTitle: "ClipMind — Create Shorts Like a Pro",
  landingMetaDescription:
    "Turn talking-head videos into captioned vertical shorts with transcript-first editing. 12 Indian languages, 9:16 export, and AI captions.",
  editorDocumentTitle: "ClipMind | Editor",
  heroSubtitle:
    "Reels, Shorts & TikTok · 12 Indian languages including Kannada, Hindi, Tamil, Telugu, and more.",
  languageCount: 12,
  featuresSectionTitle: "Everything you need to ship a short.",
  socialProofQuote: "Built for Indian creators who publish in their own language.",
  socialProofMetric: "One upload → Quick Edit → 9:16 export",
  supportedLanguages: [
    "Kannada",
    "Hindi",
    "Tamil",
    "Telugu",
    "Malayalam",
    "Marathi",
    "Bengali",
    "Gujarati",
    "Punjabi",
    "Odia",
    "Urdu",
    "English",
  ],
} as const;
